import type {
  CurrentThread,
  PastThread,
  Doc,
  ThreadBrief,
  CompilationResult,
  AskMemoryResult,
  MentionThread,
  FocusItem,
  WaitingItem,
  ArchiveItem,
  DraftSafety,
} from "./types";

export const currentThread: CurrentThread = {
  channel: "eval-infra",
  title: "Unified Eval Default Rollout",
  messages: [
    { id: "m1", author: "Alice", text: "Are we ready to make unified eval the default this week?", timestamp: "9:02 AM" },
    { id: "m2", author: "Bob", text: "Backend is merged, so I think we are good.", timestamp: "9:04 AM" },
    { id: "m3", author: "Carol", text: "Wait, I thought dashboard parity was still missing.", timestamp: "9:05 AM" },
    { id: "m4", author: "Dan", text: "Is dashboard parity actually a launch blocker? I remember we discussed this last week.", timestamp: "9:07 AM" },
    { id: "m5", author: "Alice", text: "I'm confused. Are we blocked or not? @Fanmin you were in that May 12 call.", timestamp: "9:08 AM" },
  ],
};

export const pastThreads: PastThread[] = [
  {
    id: "pt1",
    title: "Launch Readiness",
    date: "May 12",
    summary: "The team discussed whether unified eval was ready for default rollout.",
    decision: "Backend merge is allowed, but default rollout is blocked until dashboard parity is validated.",
    messages: [
      "Alice: Can we make unified eval the default next week?",
      "Carol: Only if dashboard parity is validated.",
      "Bob: Backend merge should not be blocked by dashboard parity.",
      "Alice: Decision: backend merge can proceed, but default rollout waits for dashboard parity.",
    ],
  },
  {
    id: "pt2",
    title: "Metrics Export Validation",
    date: "May 15",
    summary: "The team discussed metrics export and dashboard correctness.",
    decision: "Metrics export works, but release reporting still needs validation.",
    messages: [
      "Carol: Metrics are exporting correctly.",
      "Dan: Release reporting still does not match legacy dashboard.",
      "Alice: We should not make this default until reporting is validated.",
    ],
  },
];

export const docs: Doc[] = [
  {
    id: "doc1",
    title: "Release Validation Checklist",
    summary: "Default rollout requires dashboard parity, release reporting validation, and metrics export verification.",
    relevantSection: "Default rollout criteria",
    url: "#",
  },
  {
    id: "doc2",
    title: "Unified Eval Migration Guide",
    summary: "New workflows should use the unified_eval job format. Legacy jobs can migrate later.",
    relevantSection: "Migration path",
    url: "#",
  },
];

export const initialThreadBrief: ThreadBrief = {
  main_question: "Are we ready to make unified eval the default?",
  current_confusion: "People are mixing up backend merge and default rollout.",
  prior_decision: "Backend merge is okay. Default rollout waits for dashboard parity.",
  open_question: "Who owns dashboard validation?",
};

export const mentionThreads: MentionThread[] = [
  {
    id: "mt1",
    channel: "eval-infra",
    threadTitle: "Unified Eval Default Rollout",
    mentionedBy: "Alice",
    mentionSnippet: "Are we blocked or not? @Fanmin you were in that May 12 call.",
    relativeTime: "4m ago",
    isUnread: true,
    isActive: true,
    messages: currentThread.messages,
    threadBrief: initialThreadBrief,
  },
  {
    id: "mt2",
    channel: "platform",
    threadTitle: "API Gateway Migration",
    mentionedBy: "Bob",
    mentionSnippet: "@Fanmin migration PR is ready — can you review before standup?",
    relativeTime: "22m ago",
    isUnread: true,
    isActive: true,
    messages: [
      { id: "p1", author: "Bob", text: "Migration PR is up: adds rate limiting middleware and updated routing config.", timestamp: "8:45 AM" },
      { id: "p2", author: "Eve", text: "LGTM on routing changes. Rate limiting config looks off though — threshold seems too low.", timestamp: "8:50 AM" },
      { id: "p3", author: "Bob", text: "@Fanmin migration PR is ready — can you review before standup?", timestamp: "8:52 AM" },
    ],
    threadBrief: {
      main_question: "Is the API gateway migration PR ready to merge?",
      current_confusion: "Rate limiting threshold may be misconfigured.",
      prior_decision: "Migration was approved in last sprint planning.",
      open_question: "Who signs off on the rate limiting config?",
    },
  },
  {
    id: "mt3",
    channel: "planning",
    threadTitle: "Q3 Roadmap Review",
    mentionedBy: "Carol",
    mentionSnippet: "@Fanmin can you add eval-infra items by Thursday?",
    relativeTime: "3d ago",
    isUnread: false,
    isActive: false,
    messages: [
      { id: "q1", author: "Carol", text: "Q3 roadmap doc is live. All TLs please add your team items by Thursday.", timestamp: "May 28" },
      { id: "q2", author: "Alice", text: "ML platform items added.", timestamp: "May 28" },
      { id: "q3", author: "Carol", text: "@Fanmin can you add eval-infra items by Thursday?", timestamp: "May 28" },
    ],
    threadBrief: {
      main_question: "Has eval-infra added their Q3 roadmap items?",
      current_confusion: "Waiting on Fanmin's input.",
      prior_decision: "All TLs to submit roadmap items before Q3 kickoff.",
      open_question: "Thursday deadline — items not yet added.",
    },
  },
  {
    id: "mt4",
    channel: "infra",
    threadTitle: "DB Connection Pool Spike",
    mentionedBy: "Dan",
    mentionSnippet: "Resolved — runaway query was the cause. @Fanmin FYI",
    relativeTime: "1d ago",
    isUnread: false,
    isActive: false,
    messages: [
      { id: "d1", author: "Dan", text: "DB connections spiked to 95% at 2am. Investigating.", timestamp: "Yesterday 2:14 AM" },
      { id: "d2", author: "Eve", text: "Could be the nightly export job — it's been running long.", timestamp: "Yesterday 2:20 AM" },
      { id: "d3", author: "Dan", text: "Confirmed. Runaway query in the metrics export. Killed it, pool recovering.", timestamp: "Yesterday 2:31 AM" },
      { id: "d4", author: "Dan", text: "Resolved — connection pool was exhausted due to a runaway query. @Fanmin FYI", timestamp: "Yesterday 8:00 AM" },
    ],
    threadBrief: {
      main_question: "What caused the DB connection pool spike?",
      current_confusion: "Initially unclear — export job or app bug?",
      prior_decision: "Runaway metrics export query identified and killed.",
      open_question: "Should we add a query timeout for export jobs?",
    },
  },

  // mt5 — #oncall-p0 — Production API Degradation
  {
    id: "mt5",
    channel: "oncall-p0",
    threadTitle: "Production API Degradation",
    mentionedBy: "Bob",
    mentionSnippet: "@Fanmin need your call on rollback — prod is at 40% error rate",
    relativeTime: "8m ago",
    isUnread: true,
    isActive: true,
    messages: [
      { id: "op1", author: "PagerDuty", text: "[P0 ALERT] API error rate exceeded 5% threshold. Current: 8.3%. Service: api-gateway-prod.", timestamp: "9:02 AM" },
      { id: "op2", author: "PagerDuty", text: "[P0 ALERT] API error rate now 14.7%. Escalating to on-call.", timestamp: "9:03 AM" },
      { id: "op3", author: "Alice", text: "Acknowledged. Pulling up dashboards now.", timestamp: "9:03 AM" },
      { id: "op4", author: "Bob", text: "Joining. What's the blast radius?", timestamp: "9:04 AM" },
      { id: "op5", author: "Alice", text: "Looks like /v2/completions endpoint. 504s spiking hard.", timestamp: "9:04 AM" },
      { id: "op6", author: "Carol", text: "We deployed v2.4.1 at 8:47am. Could be related.", timestamp: "9:05 AM" },
      { id: "op7", author: "Mike", text: "Checking service logs... lots of timeout errors from the upstream model router.", timestamp: "9:05 AM" },
      { id: "op8", author: "PagerDuty", text: "[P0 ALERT] API error rate now 22.1%. SLA breach in 4 minutes.", timestamp: "9:06 AM" },
      { id: "op9", author: "Bob", text: "This is bad. Error rate climbing fast.", timestamp: "9:06 AM" },
      { id: "op10", author: "Dan", text: "I'm on. Checking if this is the new connection pooling change in v2.4.1.", timestamp: "9:06 AM" },
      { id: "op11", author: "Alice", text: "Dan — yes, there was a connection pool config change in that deploy.", timestamp: "9:07 AM" },
      { id: "op12", author: "Mike", text: "Model router is showing healthy. This is on our side.", timestamp: "9:07 AM" },
      { id: "op13", author: "Eve", text: "Latency p99 went from 280ms to 4.2s right at 8:47am deploy time.", timestamp: "9:07 AM" },
      { id: "op14", author: "Carol", text: "That timing is not a coincidence.", timestamp: "9:07 AM" },
      { id: "op15", author: "Dan", text: "Looking at the connection pool — max_connections dropped from 500 to 50 in the new config. That's the bug.", timestamp: "9:08 AM" },
      { id: "op16", author: "Bob", text: "50?! That's way too low for prod traffic.", timestamp: "9:08 AM" },
      { id: "op17", author: "Alice", text: "Can we hotfix it without a full rollback?", timestamp: "9:08 AM" },
      { id: "op18", author: "Dan", text: "We can push a config change but it needs to go through the deploy pipeline. That's 12 minutes minimum.", timestamp: "9:09 AM" },
      { id: "op19", author: "PagerDuty", text: "[P0 ALERT] API error rate now 31.6%. SLA breached.", timestamp: "9:09 AM" },
      { id: "op20", author: "Eve", text: "SLA is already breached. Every minute costs us.", timestamp: "9:09 AM" },
      { id: "op21", author: "Mike", text: "Rollback to v2.4.0 would take about 5 minutes. We have the artifact cached.", timestamp: "9:09 AM" },
      { id: "op22", author: "Carol", text: "v2.4.0 was stable for 2 weeks. I'd trust it.", timestamp: "9:10 AM" },
      { id: "op23", author: "Bob", text: "But v2.4.1 has the auth fix we needed. Rolling back means losing that.", timestamp: "9:10 AM" },
      { id: "op24", author: "Alice", text: "What's the severity of the auth bug in v2.4.0?", timestamp: "9:10 AM" },
      { id: "op25", author: "Eve", text: "Low severity — it's a corner case with expired tokens. Not exploitable.", timestamp: "9:10 AM" },
      { id: "op26", author: "Dan", text: "Error rate just hit 35%. We need to decide now.", timestamp: "9:11 AM" },
      { id: "op27", author: "Mike", text: "I can start the rollback in 30 seconds if we get the call.", timestamp: "9:11 AM" },
      { id: "op28", author: "Carol", text: "Rollback seems like the right call to me but I don't have authority here.", timestamp: "9:11 AM" },
      { id: "op29", author: "Alice", text: "We also need to confirm whether the upstream dependency had any issues overnight. Could this be a combination of factors?", timestamp: "9:11 AM" },
      { id: "op30", author: "Dan", text: "Checked upstream status page — no incidents. This is definitely the connection pool config.", timestamp: "9:12 AM" },
      { id: "op31", author: "Bob", text: "Error rate 38%. Customers are definitely seeing this.", timestamp: "9:12 AM" },
      { id: "op32", author: "Eve", text: "Support queue is spiking. 47 tickets in last 5 minutes.", timestamp: "9:12 AM" },
      { id: "op33", author: "Mike", text: "I have the rollback command ready. Waiting on TL approval.", timestamp: "9:12 AM" },
      { id: "op34", author: "Carol", text: "Whoever is TL on-call needs to make this call NOW.", timestamp: "9:13 AM" },
      { id: "op35", author: "Dan", text: "We've confirmed root cause. The config change is a clear regression.", timestamp: "9:13 AM" },
      { id: "op36", author: "Alice", text: "40% error rate. We are well into P0 territory.", timestamp: "9:13 AM" },
      { id: "op37", author: "Eve", text: "I can document the rollback for the post-mortem. Just need the go-ahead.", timestamp: "9:13 AM" },
      { id: "op38", author: "Mike", text: "Rollback ETA is 5 minutes once approved. Every minute we wait is more customer impact.", timestamp: "9:13 AM" },
      { id: "op39", author: "Bob", text: "v2.4.1 passed all staging checks but staging doesn't run at this connection volume.", timestamp: "9:14 AM" },
      { id: "op40", author: "Carol", text: "That's a known gap in our staging environment. We should fix that separately.", timestamp: "9:14 AM" },
      { id: "op41", author: "Dan", text: "Agreed — staging gap is a postmortem item. Right now: rollback decision.", timestamp: "9:14 AM" },
      { id: "op42", author: "Alice", text: "Error rate holding at ~40%. Not getting worse but not recovering.", timestamp: "9:14 AM" },
      { id: "op43", author: "Eve", text: "The new auth fix can be re-deployed as a hotfix after we stabilize. Low-risk path.", timestamp: "9:14 AM" },
      { id: "op44", author: "Mike", text: "That's a clean plan: rollback now, re-deploy auth fix as an isolated change tomorrow.", timestamp: "9:15 AM" },
      { id: "op45", author: "Bob", text: "I'm aligned. Auth fix is low severity and can wait 24 hours.", timestamp: "9:15 AM" },
      { id: "op46", author: "Carol", text: "Me too. The connection pool bug is definitely what's causing this.", timestamp: "9:15 AM" },
      { id: "op47", author: "Dan", text: "All engineers on this thread are aligned on rollback.", timestamp: "9:15 AM" },
      { id: "op48", author: "Eve", text: "Need TL sign-off to execute. Who's the on-call TL?", timestamp: "9:15 AM" },
      { id: "op49", author: "Alice", text: "Rotation schedule shows @Fanmin is on-call TL this week.", timestamp: "9:15 AM" },
      { id: "op50", author: "Mike", text: "Rollback artifact is staged and ready. Literally waiting on one person.", timestamp: "9:15 AM" },
      { id: "op51", author: "Carol", text: "41% error rate now. This is getting worse.", timestamp: "9:16 AM" },
      { id: "op52", author: "Dan", text: "Every 30 seconds we wait is thousands more failed requests.", timestamp: "9:16 AM" },
      { id: "op53", author: "Eve", text: "Support is asking if we have an ETA. I have nothing to tell them.", timestamp: "9:16 AM" },
      { id: "op54", author: "Alice", text: "We have consensus, we have the root cause, we have the fix staged.", timestamp: "9:17 AM" },
      { id: "op55", author: "Bob", text: "@Fanmin need your call on rollback — prod is at 40% error rate", timestamp: "9:17 AM" },
    ],
    threadBrief: {
      main_question: "Should we rollback the v2.4.1 deployment?",
      current_confusion: "Unclear if the spike is from the new deployment or an upstream dependency.",
      prior_decision: "v2.4.1 was deployed after passing all staging checks.",
      open_question: "Who has authority to approve the rollback?",
    },
  },

  // mt6 — #ml-pipeline — Eval Model Retraining Failure
  {
    id: "mt6",
    channel: "ml-pipeline",
    threadTitle: "Eval Model Retraining Failure",
    mentionedBy: "Alice",
    mentionSnippet: "@Fanmin the new model checkpoint is blocked on your deployment approval",
    relativeTime: "15m ago",
    isUnread: true,
    isActive: true,
    messages: [
      { id: "ml1", author: "Alice", text: "Kicking off the eval model retrain run. ETA ~3 hours.", timestamp: "6:15 AM" },
      { id: "ml2", author: "Tom", text: "Using the new dataset with the synthetic augmentation?", timestamp: "6:17 AM" },
      { id: "ml3", author: "Alice", text: "Yes — 40% synthetic, 60% human-labeled. Same split as the experiment last week.", timestamp: "6:18 AM" },
      { id: "ml4", author: "Frank", text: "Training started. Initial loss looks normal.", timestamp: "6:45 AM" },
      { id: "ml5", author: "Alice", text: "Step 500 — loss is at 1.42. Previous run was 1.51 at this point. Looking good.", timestamp: "7:30 AM" },
      { id: "ml6", author: "Tom", text: "Loss curve is cleaner than last time. Synthetic data might be helping.", timestamp: "7:45 AM" },
      { id: "ml7", author: "Frank", text: "Step 1000 — 1.31. On track.", timestamp: "8:00 AM" },
      { id: "ml8", author: "Alice", text: "Training complete. Final train loss: 1.18 vs 1.29 baseline. Nice improvement.", timestamp: "9:12 AM" },
      { id: "ml9", author: "Tom", text: "Running eval set now.", timestamp: "9:13 AM" },
      { id: "ml10", author: "Frank", text: "Checkpoint saved: eval-model-v3.2.1-ckpt-final", timestamp: "9:14 AM" },
      { id: "ml11", author: "Tom", text: "Primary eval metrics: accuracy 84.3% vs 83.1% baseline. F1: 0.847 vs 0.829. Both up.", timestamp: "9:20 AM" },
      { id: "ml12", author: "Alice", text: "That's a solid improvement on primary metrics.", timestamp: "9:21 AM" },
      { id: "ml13", author: "Frank", text: "Holdout set results coming in...", timestamp: "9:22 AM" },
      { id: "ml14", author: "Frank", text: "Holdout accuracy: 81.9% vs 83.8% baseline. That's a regression.", timestamp: "9:23 AM" },
      { id: "ml15", author: "Alice", text: "Wait — 2% regression on holdout? That's concerning.", timestamp: "9:23 AM" },
      { id: "ml16", author: "Tom", text: "Could be the holdout set has different distribution than the augmented training data.", timestamp: "9:24 AM" },
      { id: "ml17", author: "Frank", text: "Or overfitting to the synthetic examples.", timestamp: "9:24 AM" },
      { id: "ml18", author: "Alice", text: "The eval set improvement is real though. Primary metrics are clear wins.", timestamp: "9:25 AM" },
      { id: "ml19", author: "Tom", text: "Question is whether the holdout set is the right ground truth for prod behavior.", timestamp: "9:25 AM" },
      { id: "ml20", author: "Frank", text: "Our deployment threshold policy says: primary metrics must improve AND holdout regression < 1%.", timestamp: "9:26 AM" },
      { id: "ml21", author: "Alice", text: "2% is over the threshold. Technically this fails the deployment gate.", timestamp: "9:26 AM" },
      { id: "ml22", author: "Tom", text: "But the holdout set hasn't been updated in 6 months. It might not reflect current prod distribution.", timestamp: "9:27 AM" },
      { id: "ml23", author: "Frank", text: "Valid point. The holdout set staleness is a known issue.", timestamp: "9:27 AM" },
      { id: "ml24", author: "Alice", text: "I think this deserves a judgment call. The metrics are genuinely better on fresh data.", timestamp: "9:28 AM" },
      { id: "ml25", author: "Tom", text: "If we deploy this and it's actually worse in prod, that's a bad outcome.", timestamp: "9:28 AM" },
      { id: "ml26", author: "Frank", text: "Could we do a shadow deployment? Run both models for a week and compare on live traffic.", timestamp: "9:29 AM" },
      { id: "ml27", author: "Alice", text: "Shadow deploy is safe but it delays the eval model improvement by a week.", timestamp: "9:29 AM" },
      { id: "ml28", author: "Tom", text: "The current eval model has a known bias issue that this retrain was supposed to fix.", timestamp: "9:30 AM" },
      { id: "ml29", author: "Frank", text: "Right — we've had 3 escalations this week from that bias issue.", timestamp: "9:30 AM" },
      { id: "ml30", author: "Alice", text: "So the cost of waiting is real too.", timestamp: "9:31 AM" },
      { id: "ml31", author: "Tom", text: "I'd vote to deploy with monitoring. But I don't have deployment authority.", timestamp: "9:31 AM" },
      { id: "ml32", author: "Frank", text: "Policy is clear: TL approval required for any model deployment.", timestamp: "9:32 AM" },
      { id: "ml33", author: "Alice", text: "Let me check if there's an exception process for stale holdout sets.", timestamp: "9:32 AM" },
      { id: "ml34", author: "Tom", text: "There isn't one documented. This would be a first.", timestamp: "9:33 AM" },
      { id: "ml35", author: "Frank", text: "I can refresh the holdout set but that takes 2 days to re-label.", timestamp: "9:33 AM" },
      { id: "ml36", author: "Alice", text: "Two days is too long. The bias issue is causing real problems now.", timestamp: "9:34 AM" },
      { id: "ml37", author: "Tom", text: "Options as I see them: 1) Deploy with monitoring 2) Shadow deploy 3) Refresh holdout and re-evaluate 4) Reject this checkpoint.", timestamp: "9:35 AM" },
      { id: "ml38", author: "Frank", text: "Option 4 seems wrong given the primary metrics. We'd be regressing to a model we know is biased.", timestamp: "9:35 AM" },
      { id: "ml39", author: "Alice", text: "I agree. The question is between 1 and 2.", timestamp: "9:36 AM" },
      { id: "ml40", author: "Tom", text: "Shadow deploy gives us safety. Direct deploy gives us speed.", timestamp: "9:36 AM" },
      { id: "ml41", author: "Frank", text: "Given the bias escalations, I lean toward direct deploy with tight monitoring.", timestamp: "9:37 AM" },
      { id: "ml42", author: "Alice", text: "What monitoring would we need? We'd want p95 latency, accuracy proxy metrics, and user feedback signals.", timestamp: "9:37 AM" },
      { id: "ml43", author: "Tom", text: "We have all of those in the eval dashboard. Could set up alerts for immediate rollback if needed.", timestamp: "9:38 AM" },
      { id: "ml44", author: "Frank", text: "Rollback SLA for model is 30 minutes. That's acceptable blast radius.", timestamp: "9:38 AM" },
      { id: "ml45", author: "Alice", text: "I think we have enough analysis to bring this to TL. The decision is: accept 2% holdout regression given stale holdout set and bias urgency?", timestamp: "9:39 AM" },
      { id: "ml46", author: "Tom", text: "That's exactly the question.", timestamp: "9:39 AM" },
      { id: "ml47", author: "Frank", text: "Checkpoint is validated and staged. Ready to deploy on approval.", timestamp: "9:40 AM" },
      { id: "ml48", author: "Alice", text: "All model deployments require TL approval per policy. We need a sign-off.", timestamp: "9:40 AM" },
      { id: "ml49", author: "Tom", text: "Can we get this done quickly? The bias issue is getting escalated again today.", timestamp: "9:41 AM" },
      { id: "ml50", author: "Frank", text: "Deployment pipeline is ready. Just waiting on the approval gate.", timestamp: "9:41 AM" },
      { id: "ml51", author: "Alice", text: "I'll flag it. @Fanmin the new model checkpoint is blocked on your deployment approval", timestamp: "9:44 AM" },
      { id: "ml52", author: "Tom", text: "Summary for @Fanmin: train loss improved 8.5%, primary eval metrics up 1.2-1.8%, holdout shows 2% regression (holdout set is 6 months stale). Bias fix is urgently needed.", timestamp: "9:44 AM" },
    ],
    threadBrief: {
      main_question: "Can we deploy the retrained eval model to production?",
      current_confusion: "Training metrics improved but eval set performance is ambiguous.",
      prior_decision: "All model deployments require TL approval.",
      open_question: "Is the 2% regression on the holdout set acceptable?",
    },
  },

  // mt7 — #security — CVE-2025-4821 in Auth Library
  {
    id: "mt7",
    channel: "security",
    threadTitle: "CVE-2025-4821 in Auth Library",
    mentionedBy: "Eve",
    mentionSnippet: "@Fanmin this CVE affects our auth flow — need your sign-off on the patch plan",
    relativeTime: "32m ago",
    isUnread: true,
    isActive: true,
    messages: [
      { id: "sec1", author: "Eve", text: "CVE-2025-4821 just dropped. CVSS 9.1 — critical severity in auth-lib versions < 4.2.3.", timestamp: "8:45 AM" },
      { id: "sec2", author: "Mike", text: "What's the exploit vector?", timestamp: "8:46 AM" },
      { id: "sec3", author: "Eve", text: "JWT validation bypass via malformed algorithm header. Attacker can forge tokens.", timestamp: "8:46 AM" },
      { id: "sec4", author: "Alice", text: "Oh that's bad. Which version are we on?", timestamp: "8:47 AM" },
      { id: "sec5", author: "Tom", text: "Checking... we're on auth-lib 4.1.8 across all services.", timestamp: "8:47 AM" },
      { id: "sec6", author: "Eve", text: "That's affected. We need to patch.", timestamp: "8:48 AM" },
      { id: "sec7", author: "Bob", text: "How many services use auth-lib?", timestamp: "8:48 AM" },
      { id: "sec8", author: "Tom", text: "Running the scan now... api-gateway, user-service, session-manager, admin-portal. 4 services.", timestamp: "8:49 AM" },
      { id: "sec9", author: "Eve", text: "All 4 are in the blast radius. This is our entire auth stack.", timestamp: "8:49 AM" },
      { id: "sec10", author: "Mike", text: "Is this being actively exploited in the wild?", timestamp: "8:50 AM" },
      { id: "sec11", author: "Eve", text: "NVD says PoC exists but no confirmed active exploitation yet. That changes fast.", timestamp: "8:50 AM" },
      { id: "sec12", author: "Alice", text: "What are the patch options?", timestamp: "8:51 AM" },
      { id: "sec13", author: "Eve", text: "Option 1: Emergency patch to auth-lib 4.2.3-emergency. Released yesterday, fixes the CVE.", timestamp: "8:51 AM" },
      { id: "sec14", author: "Tom", text: "There's an Option 2?", timestamp: "8:52 AM" },
      { id: "sec15", author: "Eve", text: "Option 2: Wait for stable 4.3.0 release, expected next Tuesday. Full test coverage, no breaking changes.", timestamp: "8:52 AM" },
      { id: "sec16", author: "Bob", text: "What's the catch with the emergency patch?", timestamp: "8:52 AM" },
      { id: "sec17", author: "Eve", text: "4.2.3-emergency changes session token format. Any existing sessions will be invalidated on upgrade.", timestamp: "8:53 AM" },
      { id: "sec18", author: "Alice", text: "That means all logged-in users get logged out.", timestamp: "8:53 AM" },
      { id: "sec19", author: "Tom", text: "How many active sessions are we talking?", timestamp: "8:54 AM" },
      { id: "sec20", author: "Mike", text: "About 180k active sessions right now.", timestamp: "8:54 AM" },
      { id: "sec21", author: "Bob", text: "Mass logout during business hours. That's going to generate support tickets.", timestamp: "8:54 AM" },
      { id: "sec22", author: "Eve", text: "Our security policy says critical CVEs must be patched within 24 hours. Clock started at 8:45am.", timestamp: "8:55 AM" },
      { id: "sec23", author: "Alice", text: "So we have until 8:45am tomorrow. That's actually enough time to wait for stable.", timestamp: "8:55 AM" },
      { id: "sec24", author: "Tom", text: "Stable isn't until Tuesday. That's 4 days. We'd be in violation.", timestamp: "8:56 AM" },
      { id: "sec25", author: "Mike", text: "So the choice is really: emergency patch now (breaking) vs policy violation (4 days unpatched).", timestamp: "8:56 AM" },
      { id: "sec26", author: "Eve", text: "There's also a WAF mitigation option. We can add a rule to block malformed JWT headers at the edge.", timestamp: "8:57 AM" },
      { id: "sec27", author: "Bob", text: "Is WAF mitigation considered sufficient for the 24h SLA?", timestamp: "8:57 AM" },
      { id: "sec28", author: "Eve", text: "Security team says it's a compensating control, not a fix. SLA still applies.", timestamp: "8:58 AM" },
      { id: "sec29", author: "Alice", text: "Could we apply WAF mitigation now and deploy the emergency patch tonight during low traffic?", timestamp: "8:58 AM" },
      { id: "sec30", author: "Tom", text: "That's actually a decent middle path. WAF covers us immediately, session disruption happens at 2am when fewer users are active.", timestamp: "8:59 AM" },
      { id: "sec31", author: "Mike", text: "2am maintenance window would reduce session disruption from 180k to maybe 20k users.", timestamp: "8:59 AM" },
      { id: "sec32", author: "Eve", text: "I like that plan. WAF rule goes up immediately, emergency patch at 2am.", timestamp: "9:00 AM" },
      { id: "sec33", author: "Bob", text: "What's the rollback plan if the emergency patch breaks something else?", timestamp: "9:00 AM" },
      { id: "sec34", author: "Tom", text: "We'd roll back to 4.1.8 which is vulnerable again. Not ideal.", timestamp: "9:01 AM" },
      { id: "sec35", author: "Alice", text: "Could we upgrade to 4.2.2 which doesn't have the session breaking change?", timestamp: "9:01 AM" },
      { id: "sec36", author: "Eve", text: "4.2.2 is also vulnerable to CVE-2025-4821. Only 4.2.3-emergency has the fix.", timestamp: "9:02 AM" },
      { id: "sec37", author: "Mike", text: "So our options are: vulnerable (4.1.8 or 4.2.2) or breaking change (4.2.3-emergency).", timestamp: "9:02 AM" },
      { id: "sec38", author: "Bob", text: "When is 4.3.0 stable actually releasing?", timestamp: "9:03 AM" },
      { id: "sec39", author: "Eve", text: "Auth-lib maintainers say Tuesday. But that slipped once already.", timestamp: "9:03 AM" },
      { id: "sec40", author: "Tom", text: "I would not count on Tuesday.", timestamp: "9:04 AM" },
      { id: "sec41", author: "Alice", text: "Then it's emergency patch or policy violation. Those are the real choices.", timestamp: "9:04 AM" },
      { id: "sec42", author: "Mike", text: "From a pure security standpoint: patch now. The CVE is critical.", timestamp: "9:05 AM" },
      { id: "sec43", author: "Bob", text: "From a user experience standpoint: session disruption is painful but recoverable.", timestamp: "9:05 AM" },
      { id: "sec44", author: "Eve", text: "Can we notify users before the 2am patch? Give them a heads up.", timestamp: "9:06 AM" },
      { id: "sec45", author: "Tom", text: "We could send a banner notification. 'We will be performing security maintenance at 2am PT. You will be asked to log in again.'", timestamp: "9:06 AM" },
      { id: "sec46", author: "Alice", text: "That's reasonable. Keeps users informed, reduces surprise factor.", timestamp: "9:07 AM" },
      { id: "sec47", author: "Mike", text: "The full plan: WAF rule now, user notification at 6pm, emergency patch at 2am.", timestamp: "9:07 AM" },
      { id: "sec48", author: "Bob", text: "I think that's solid. But we need TL sign-off on the patch plan.", timestamp: "9:08 AM" },
      { id: "sec49", author: "Tom", text: "Especially on the decision to use the emergency patch vs waiting for stable.", timestamp: "9:08 AM" },
      { id: "sec50", author: "Alice", text: "Security decisions of this scope need TL approval.", timestamp: "9:09 AM" },
      { id: "sec51", author: "Eve", text: "@Fanmin this CVE affects our auth flow — need your sign-off on the patch plan", timestamp: "9:13 AM" },
    ],
    threadBrief: {
      main_question: "Do we apply the emergency patch or wait for the stable release?",
      current_confusion: "Emergency patch fixes the CVE but introduces a breaking change in session handling.",
      prior_decision: "Security patches for critical CVEs must be applied within 24 hours.",
      open_question: "Can we absorb the session handling breakage before EOD?",
    },
  },

  // mt8 — #product — Q3 Launch Go/No-Go
  {
    id: "mt8",
    channel: "product",
    threadTitle: "Q3 Launch Go/No-Go",
    mentionedBy: "Sarah",
    mentionSnippet: "@Fanmin we need your go/no-go by 3pm or the launch window closes",
    relativeTime: "1h ago",
    isUnread: true,
    isActive: true,
    messages: [
      { id: "pr1", author: "Sarah", text: "Launch readiness check starting now. Window opens at 2pm PT. Let's go through each area.", timestamp: "8:00 AM" },
      { id: "pr2", author: "Mike", text: "Engineering status: feature code is complete and merged. QA passed last night.", timestamp: "8:02 AM" },
      { id: "pr3", author: "Jenny", text: "Design: all assets are exported and in the CDN. Mobile and desktop responsive.", timestamp: "8:03 AM" },
      { id: "pr4", author: "Tom", text: "Backend APIs: v2 endpoints are live in staging. Load tested to 10x expected traffic.", timestamp: "8:04 AM" },
      { id: "pr5", author: "Frank", text: "Data pipeline: events are firing correctly in staging. Analytics dashboards ready.", timestamp: "8:05 AM" },
      { id: "pr6", author: "Sarah", text: "Legal status?", timestamp: "8:05 AM" },
      { id: "pr7", author: "Carol", text: "Legal cleared the feature copy and data handling yesterday afternoon. No issues.", timestamp: "8:06 AM" },
      { id: "pr8", author: "Sarah", text: "Marketing — are we ready?", timestamp: "8:06 AM" },
      { id: "pr9", author: "Alice", text: "Marketing: email campaign is scheduled, social posts are drafted, blog post is ready to publish.", timestamp: "8:07 AM" },
      { id: "pr10", author: "Sarah", text: "This is looking good. What's the blocker list?", timestamp: "8:08 AM" },
      { id: "pr11", author: "Mike", text: "We have one open item: the payments edge case.", timestamp: "8:08 AM" },
      { id: "pr12", author: "Tom", text: "What's the payments edge case?", timestamp: "8:09 AM" },
      { id: "pr13", author: "Mike", text: "When a user has a saved card with an expired CVV and tries to complete checkout with the new flow, the error message is wrong. Shows a generic error instead of 'update your card'.", timestamp: "8:09 AM" },
      { id: "pr14", author: "Frank", text: "Is the payment itself failing or just the error message?", timestamp: "8:10 AM" },
      { id: "pr15", author: "Mike", text: "The payment correctly declines (good), but the UX message is misleading.", timestamp: "8:10 AM" },
      { id: "pr16", author: "Jenny", text: "How many users have saved cards with expired CVVs?", timestamp: "8:11 AM" },
      { id: "pr17", author: "Frank", text: "Ran the query: ~2.3% of active users have this card state.", timestamp: "8:11 AM" },
      { id: "pr18", author: "Tom", text: "So 2.3% of users who attempt checkout could see a confusing error. Not launch-blocking in my view.", timestamp: "8:12 AM" },
      { id: "pr19", author: "Mike", text: "But those users would likely abandon their cart and contact support.", timestamp: "8:12 AM" },
      { id: "pr20", author: "Alice", text: "That's potentially hundreds of support tickets on launch day.", timestamp: "8:13 AM" },
      { id: "pr21", author: "Carol", text: "Legal said the copy was fine — does this change their review since the error message is different?", timestamp: "8:13 AM" },
      { id: "pr22", author: "Sarah", text: "Good question. Carol can you check with legal on this specific error message?", timestamp: "8:14 AM" },
      { id: "pr23", author: "Carol", text: "On it. They usually respond within the hour.", timestamp: "8:14 AM" },
      { id: "pr24", author: "Mike", text: "In parallel: how hard is the fix?", timestamp: "8:15 AM" },
      { id: "pr25", author: "Tom", text: "It's a one-line string change. 30 minutes to fix, 2 hours to get through pipeline including QA.", timestamp: "8:15 AM" },
      { id: "pr26", author: "Frank", text: "If we start now we could have it fixed before the 2pm launch window.", timestamp: "8:16 AM" },
      { id: "pr27", author: "Mike", text: "I can start on the fix right now if we decide it's a blocker.", timestamp: "8:16 AM" },
      { id: "pr28", author: "Sarah", text: "Or we could launch with the bug and hotfix post-launch. The core functionality works.", timestamp: "8:17 AM" },
      { id: "pr29", author: "Jenny", text: "Launch-with-hotfix is risky on day one. Users form first impressions quickly.", timestamp: "8:17 AM" },
      { id: "pr30", author: "Alice", text: "Marketing campaign has already sent pre-launch emails. Rolling back launch has costs too.", timestamp: "8:18 AM" },
      { id: "pr31", author: "Tom", text: "Can we A/B the launch? Exclude users with expired CVV cards from the new flow on day one?", timestamp: "8:19 AM" },
      { id: "pr32", author: "Frank", text: "We have the flag infrastructure for that. It would take about 45 minutes to set up.", timestamp: "8:19 AM" },
      { id: "pr33", author: "Mike", text: "That's actually elegant. Launch to 97.7% of users on day one, fix the bug, then roll out to the rest.", timestamp: "8:20 AM" },
      { id: "pr34", author: "Sarah", text: "I like that approach. Does everyone agree?", timestamp: "8:21 AM" },
      { id: "pr35", author: "Jenny", text: "Yes — it's pragmatic and protects the user experience.", timestamp: "8:21 AM" },
      { id: "pr36", author: "Tom", text: "Agreed. Frank can you start on the exclusion flag?", timestamp: "8:22 AM" },
      { id: "pr37", author: "Frank", text: "Starting now.", timestamp: "8:22 AM" },
      { id: "pr38", author: "Carol", text: "Legal replied: the error message issue doesn't affect their clearance since payment decline behavior is correct. We're clear.", timestamp: "8:45 AM" },
      { id: "pr39", author: "Sarah", text: "Great. So legal is clear, we have the exclusion flag as a safety net. Are there any other blockers?", timestamp: "8:46 AM" },
      { id: "pr40", author: "Mike", text: "Nothing else from eng.", timestamp: "8:47 AM" },
      { id: "pr41", author: "Alice", text: "Marketing is ready to go.", timestamp: "8:47 AM" },
      { id: "pr42", author: "Jenny", text: "Design is ready.", timestamp: "8:47 AM" },
      { id: "pr43", author: "Frank", text: "Exclusion flag is implemented and tested. Ready to enable.", timestamp: "9:15 AM" },
      { id: "pr44", author: "Tom", text: "Pipeline complete. All checks green.", timestamp: "9:18 AM" },
      { id: "pr45", author: "Sarah", text: "Okay. We're 2 hours from the launch window. Everything looks ready.", timestamp: "9:20 AM" },
      { id: "pr46", author: "Mike", text: "Who makes the final go/no-go call?", timestamp: "9:21 AM" },
      { id: "pr47", author: "Carol", text: "Per our launch process, the TL makes the final go/no-go decision.", timestamp: "9:21 AM" },
      { id: "pr48", author: "Sarah", text: "That's Fanmin for this feature set.", timestamp: "9:22 AM" },
      { id: "pr49", author: "Alice", text: "We need that call before 3pm or the launch window closes and we push to next week.", timestamp: "9:22 AM" },
      { id: "pr50", author: "Tom", text: "Pushing to next week would mean rescheduling the marketing campaign and PR. Not ideal.", timestamp: "9:23 AM" },
      { id: "pr51", author: "Frank", text: "The team is ready. Everything is green. Just waiting on the official go.", timestamp: "9:23 AM" },
      { id: "pr52", author: "Jenny", text: "Designers are on standby for any last-minute tweaks.", timestamp: "9:24 AM" },
      { id: "pr53", author: "Mike", text: "Eng team is ready to flip the switch.", timestamp: "9:24 AM" },
      { id: "pr54", author: "Carol", text: "Legal is cleared. Marketing is ready. Eng is ready.", timestamp: "9:24 AM" },
      { id: "pr55", author: "Alice", text: "We've never been this ready for a launch. Genuinely impressive teamwork everyone.", timestamp: "9:25 AM" },
      { id: "pr56", author: "Tom", text: "Still need the formal go/no-go though.", timestamp: "9:25 AM" },
      { id: "pr57", author: "Frank", text: "The clock is ticking. 3pm deadline.", timestamp: "9:26 AM" },
      { id: "pr58", author: "Sarah", text: "@Fanmin we need your go/no-go by 3pm or the launch window closes", timestamp: "9:30 AM" },
    ],
    threadBrief: {
      main_question: "Are we launching the Q3 feature set today?",
      current_confusion: "Legal cleared it but eng flagged a last-minute edge case in payments.",
      prior_decision: "Launch window is 2pm–4pm PT to minimize user impact.",
      open_question: "Does the payments edge case block launch or can it be hotfixed post-launch?",
    },
  },

  // mt9 — #design-review — Checkout Flow Redesign
  {
    id: "mt9",
    channel: "design-review",
    threadTitle: "Checkout Flow Redesign",
    mentionedBy: "Jenny",
    mentionSnippet: "@Fanmin designs ship tomorrow at 9am and you haven't approved yet",
    relativeTime: "2h ago",
    isUnread: true,
    isActive: false,
    messages: [
      { id: "dr1", author: "Jenny", text: "Sharing the initial checkout flow redesign mockups. Figma link: figma.com/checkout-v2", timestamp: "2 days ago 10:00 AM" },
      { id: "dr2", author: "Tom", text: "These look great. The new step indicator is much clearer.", timestamp: "2 days ago 10:15 AM" },
      { id: "dr3", author: "Alice", text: "Love the progress bar. Question: can the 'Back' button be more prominent?", timestamp: "2 days ago 10:22 AM" },
      { id: "dr4", author: "Jenny", text: "Good note. I'll increase the back button size.", timestamp: "2 days ago 10:30 AM" },
      { id: "dr5", author: "Frank", text: "From engineering: the card input layout will be tricky on mobile. Inputs are too close together.", timestamp: "2 days ago 11:00 AM" },
      { id: "dr6", author: "Jenny", text: "Good catch. Mobile mockup coming in v2.", timestamp: "2 days ago 11:10 AM" },
      { id: "dr7", author: "Mike", text: "What's the accessibility status? Screen reader compatibility?", timestamp: "2 days ago 11:30 AM" },
      { id: "dr8", author: "Jenny", text: "Running axe audit now. Will share results.", timestamp: "2 days ago 11:35 AM" },
      { id: "dr9", author: "Carol", text: "The 'Place Order' CTA copy — legal had concerns about implied commitments. Is this cleared?", timestamp: "2 days ago 12:00 PM" },
      { id: "dr10", author: "Jenny", text: "I'll check with legal. They reviewed the original 'Complete Purchase' copy but we changed it to 'Place Order'.", timestamp: "2 days ago 12:08 PM" },
      { id: "dr11", author: "Tom", text: "Axe audit results: 3 issues — missing alt text on card icons, low contrast on helper text, tab order issue on the CVV field.", timestamp: "2 days ago 1:00 PM" },
      { id: "dr12", author: "Jenny", text: "Fixing all three in v2. Should have v2 up by EOD.", timestamp: "2 days ago 1:15 PM" },
      { id: "dr13", author: "Alice", text: "Reminder: TL needs to sign off before eng starts implementation.", timestamp: "2 days ago 1:20 PM" },
      { id: "dr14", author: "Jenny", text: "@Fanmin can you take a look when you have a moment? Figma: figma.com/checkout-v2", timestamp: "2 days ago 1:25 PM" },
      { id: "dr15", author: "Frank", text: "v2 is up. Mobile layout is much better.", timestamp: "2 days ago 4:00 PM" },
      { id: "dr16", author: "Mike", text: "Accessibility issues are all fixed in v2.", timestamp: "2 days ago 4:15 PM" },
      { id: "dr17", author: "Tom", text: "Card input spacing on mobile looks good now.", timestamp: "2 days ago 4:20 PM" },
      { id: "dr18", author: "Carol", text: "Legal responded: 'Place Order' copy is cleared.", timestamp: "2 days ago 4:45 PM" },
      { id: "dr19", author: "Jenny", text: "v2 is the final version pending TL approval. Waiting on @Fanmin.", timestamp: "2 days ago 5:00 PM" },
      { id: "dr20", author: "Alice", text: "Still need TL approval before we can start implementation.", timestamp: "Yesterday 9:00 AM" },
      { id: "dr21", author: "Frank", text: "Eng is ready to start once we get the green light. Blocked on approval.", timestamp: "Yesterday 9:15 AM" },
      { id: "dr22", author: "Jenny", text: "Pinged @Fanmin directly on Slack. No response yet.", timestamp: "Yesterday 10:00 AM" },
      { id: "dr23", author: "Tom", text: "Timeline is getting tight. Designs were supposed to be approved Monday.", timestamp: "Yesterday 11:00 AM" },
      { id: "dr24", author: "Mike", text: "If eng doesn't start today we'll miss the Thursday implementation deadline.", timestamp: "Yesterday 11:30 AM" },
      { id: "dr25", author: "Carol", text: "Implementation takes 3 days. Thursday deadline means today is the last day to start.", timestamp: "Yesterday 12:00 PM" },
      { id: "dr26", author: "Jenny", text: "Revised the CTA copy one more time based on user research — 'Confirm & Pay' tested better. Updating Figma.", timestamp: "Yesterday 1:00 PM" },
      { id: "dr27", author: "Alice", text: "Wait, does the copy change need another legal review?", timestamp: "Yesterday 1:15 PM" },
      { id: "dr28", author: "Carol", text: "Depends on how different it is from the cleared version. 'Confirm & Pay' vs 'Place Order' — could be flagged.", timestamp: "Yesterday 1:20 PM" },
      { id: "dr29", author: "Jenny", text: "I'll ask legal for a quick review. They've been responsive.", timestamp: "Yesterday 1:25 PM" },
      { id: "dr30", author: "Tom", text: "So now we have v3 with new copy AND still no TL approval. This is getting complicated.", timestamp: "Yesterday 1:30 PM" },
      { id: "dr31", author: "Frank", text: "Eng timeline is slipping. We needed to start yesterday.", timestamp: "Yesterday 2:00 PM" },
      { id: "dr32", author: "Mike", text: "At this rate we won't make Thursday.", timestamp: "Yesterday 2:30 PM" },
      { id: "dr33", author: "Jenny", text: "Legal quick-reviewed 'Confirm & Pay' — cleared. So v3 is legally clean.", timestamp: "Yesterday 3:00 PM" },
      { id: "dr34", author: "Alice", text: "Good. But the TL approval is still missing and we're on v3 now. TL hasn't seen v2 or v3.", timestamp: "Yesterday 3:15 PM" },
      { id: "dr35", author: "Carol", text: "Does TL need to re-approve both v2 and v3 changes? Or just v3 as the final?", timestamp: "Yesterday 3:20 PM" },
      { id: "dr36", author: "Tom", text: "Process says: TL signs off on final design before implementation starts.", timestamp: "Yesterday 3:25 PM" },
      { id: "dr37", author: "Jenny", text: "v3 is final. That's what TL needs to approve.", timestamp: "Yesterday 3:30 PM" },
      { id: "dr38", author: "Frank", text: "Can we start implementation in parallel and treat approval as a formality?", timestamp: "Yesterday 4:00 PM" },
      { id: "dr39", author: "Alice", text: "No — process exists for a reason. We don't want to implement something that gets rejected.", timestamp: "Yesterday 4:05 PM" },
      { id: "dr40", author: "Mike", text: "The v3 changes are minor. Back button size, mobile spacing, copy. TL approved the direction in an earlier design review.", timestamp: "Yesterday 4:10 PM" },
      { id: "dr41", author: "Tom", text: "Earlier approval doesn't count as approval for the current designs. Those were early concepts.", timestamp: "Yesterday 4:15 PM" },
      { id: "dr42", author: "Carol", text: "Timeline is now critical. Designs ship tomorrow and implementation needs to start immediately after.", timestamp: "Yesterday 4:30 PM" },
      { id: "dr43", author: "Jenny", text: "Sent another direct message to @Fanmin. Still no response.", timestamp: "Yesterday 5:00 PM" },
      { id: "dr44", author: "Frank", text: "This is becoming a blocker. Eng can't start without approval.", timestamp: "Yesterday 5:15 PM" },
      { id: "dr45", author: "Alice", text: "Should we escalate to @Fanmin's manager?", timestamp: "Yesterday 5:20 PM" },
      { id: "dr46", author: "Tom", text: "Let's give it until end of day tomorrow. The designs ship at 9am and that's the real deadline.", timestamp: "Yesterday 5:25 PM" },
      { id: "dr47", author: "Mike", text: "If we don't have approval by 9am tomorrow, what's the plan?", timestamp: "Yesterday 5:30 PM" },
      { id: "dr48", author: "Carol", text: "We'd have to delay the implementation start by another day. Launch date would slip.", timestamp: "Yesterday 5:35 PM" },
      { id: "dr49", author: "Frank", text: "Eng team has capacity today and tomorrow. After that we have other projects starting.", timestamp: "Yesterday 5:40 PM" },
      { id: "dr50", author: "Jenny", text: "@Fanmin designs ship tomorrow at 9am and you haven't approved yet", timestamp: "Today 7:15 AM" },
    ],
    threadBrief: {
      main_question: "Are the checkout redesign mockups approved for implementation?",
      current_confusion: "Two rounds of revisions happened after the initial review — not clear if the current version was re-approved.",
      prior_decision: "TL must sign off before eng begins implementation.",
      open_question: "Does the updated CTA copy need another round of legal review?",
    },
  },

  // mt10 — #general — Random team chatter
  {
    id: "mt10",
    channel: "general",
    threadTitle: "Random team chatter",
    mentionedBy: "Dan",
    mentionSnippet: "Good morning everyone!",
    relativeTime: "3h ago",
    isUnread: false,
    isActive: false,
    messages: [
      { id: "gen1", author: "Dan", text: "Good morning everyone! ☀️", timestamp: "7:00 AM" },
      { id: "gen2", author: "Alice", text: "Morning! Did anyone catch the game last night?", timestamp: "7:02 AM" },
      { id: "gen3", author: "Bob", text: "YES. That last quarter was insane.", timestamp: "7:03 AM" },
      { id: "gen4", author: "Carol", text: "I fell asleep in the third. Don't spoil it.", timestamp: "7:04 AM" },
      { id: "gen5", author: "Mike", text: "lol Carol", timestamp: "7:04 AM" },
      { id: "gen6", author: "Tom", text: "Morning all. Does anyone know if the coffee machine on floor 3 is fixed?", timestamp: "7:05 AM" },
      { id: "gen7", author: "Dan", text: "It was broken as of yesterday afternoon. Floor 2 machine works.", timestamp: "7:06 AM" },
      { id: "gen8", author: "Tom", text: "Thank you. Trekking to floor 2 it is.", timestamp: "7:07 AM" },
      { id: "gen9", author: "Frank", text: "Has anyone tried that new ramen place on 5th?", timestamp: "7:10 AM" },
      { id: "gen10", author: "Alice", text: "Yes! The tonkotsu is incredible.", timestamp: "7:11 AM" },
      { id: "gen11", author: "Jenny", text: "Adding it to the team lunch rotation.", timestamp: "7:12 AM" },
      { id: "gen12", author: "Bob", text: "Team lunch when? I'm always the last to know.", timestamp: "7:13 AM" },
      { id: "gen13", author: "Carol", text: "Because you never read #team-events Bob 😂", timestamp: "7:13 AM" },
      { id: "gen14", author: "Mike", text: "This meme is so accurate it hurts: [image of developer staring at screen]", timestamp: "7:15 AM" },
      { id: "gen15", author: "Dan", text: "LMAO that's me every Monday morning", timestamp: "7:16 AM" },
      { id: "gen16", author: "Eve", text: "Morning everyone. Quick PSA: the parking garage B elevators are out until Thursday.", timestamp: "7:20 AM" },
      { id: "gen17", author: "Tom", text: "Thanks Eve. The parking garage news you didn't know you needed.", timestamp: "7:21 AM" },
      { id: "gen18", author: "Frank", text: "Speaking of elevators — I got stuck in the main building elevator last week for 20 minutes", timestamp: "7:22 AM" },
      { id: "gen19", author: "Alice", text: "Frank that's terrifying! Are you okay?", timestamp: "7:23 AM" },
      { id: "gen20", author: "Frank", text: "Totally fine, just stressful. There was one other person in there and we ended up talking about our favorite 90s cartoons.", timestamp: "7:24 AM" },
      { id: "gen21", author: "Bob", text: "Name a better way to bond with a coworker. I'll wait.", timestamp: "7:25 AM" },
      { id: "gen22", author: "Carol", text: "Happy birthday to Sarah today! 🎂", timestamp: "7:30 AM" },
      { id: "gen23", author: "Dan", text: "Happy birthday Sarah!!! 🎉", timestamp: "7:30 AM" },
      { id: "gen24", author: "Mike", text: "HBD! 🎂", timestamp: "7:31 AM" },
      { id: "gen25", author: "Jenny", text: "Happy birthday!! hope you're doing something fun this weekend", timestamp: "7:31 AM" },
      { id: "gen26", author: "Sarah", text: "aww thank you all!! I'm getting brunch with my family this weekend 😊", timestamp: "7:45 AM" },
      { id: "gen27", author: "Tom", text: "Brunch > everything. Happy birthday!", timestamp: "7:46 AM" },
      { id: "gen28", author: "Alice", text: "Has anyone seen the new article about LLMs and chess? https://example.com/llm-chess", timestamp: "7:50 AM" },
      { id: "gen29", author: "Bob", text: "Oh interesting. Sending to my chess club.", timestamp: "7:52 AM" },
      { id: "gen30", author: "Frank", text: "I didn't know you played chess Bob", timestamp: "7:53 AM" },
      { id: "gen31", author: "Bob", text: "Competitively. Don't let that distract from my deeply uninteresting exterior.", timestamp: "7:54 AM" },
      { id: "gen32", author: "Carol", text: "lol 'deeply uninteresting exterior'", timestamp: "7:55 AM" },
      { id: "gen33", author: "Dan", text: "What is everyone having for lunch today? I'm between the salad bar and the new ramen place.", timestamp: "8:00 AM" },
      { id: "gen34", author: "Mike", text: "Ramen. Obviously ramen.", timestamp: "8:01 AM" },
      { id: "gen35", author: "Eve", text: "I brought leftovers. Tacos from last night.", timestamp: "8:01 AM" },
      { id: "gen36", author: "Alice", text: "Jealous of the tacos tbh", timestamp: "8:02 AM" },
      { id: "gen37", author: "Tom", text: "Anyone want to do a group lunch at ramen? 12:30?", timestamp: "8:05 AM" },
      { id: "gen38", author: "Jenny", text: "I'm in!", timestamp: "8:06 AM" },
      { id: "gen39", author: "Frank", text: "In!", timestamp: "8:06 AM" },
      { id: "gen40", author: "Bob", text: "Can't, have a 12:30 meeting. Next time for sure.", timestamp: "8:07 AM" },
      { id: "gen41", author: "Carol", text: "I'll join you Tom.", timestamp: "8:07 AM" },
      { id: "gen42", author: "Dan", text: "Ramen crew forming. I'll make a reservation.", timestamp: "8:08 AM" },
      { id: "gen43", author: "Mike", text: "Does anyone else think the new office playlist is too loud? I can hear it through my headphones.", timestamp: "8:10 AM" },
      { id: "gen44", author: "Alice", text: "YES. I submitted a facilities ticket about it last week.", timestamp: "8:11 AM" },
      { id: "gen45", author: "Tom", text: "Facilities tickets go to die. I filed one 3 months ago about the broken chair in room 4B.", timestamp: "8:12 AM" },
      { id: "gen46", author: "Eve", text: "The chair is still broken. I sat in it yesterday.", timestamp: "8:13 AM" },
      { id: "gen47", author: "Frank", text: "At least the elevator trauma gave you a conversation partner Tom", timestamp: "8:14 AM" },
      { id: "gen48", author: "Tom", text: "That was me not Frank. But yes, silver linings.", timestamp: "8:15 AM" },
      { id: "gen49", author: "Bob", text: "Sharing this absolutely cursed PR description I just found in our old repos: 'Fixed the thing that was broken. Works now.'", timestamp: "8:20 AM" },
      { id: "gen50", author: "Carol", text: "Who wrote that 💀", timestamp: "8:21 AM" },
      { id: "gen51", author: "Mike", text: "The commit message is probably just 'fix'", timestamp: "8:22 AM" },
      { id: "gen52", author: "Jenny", text: "We have all committed crimes like this. No judgment.", timestamp: "8:23 AM" },
      { id: "gen53", author: "Dan", text: "Ramen reservation is confirmed for 12:30. Party of 5.", timestamp: "8:25 AM" },
      { id: "gen54", author: "Alice", text: "What's the name of the place? Sending to a friend who wants to try it too.", timestamp: "8:26 AM" },
      { id: "gen55", author: "Tom", text: "Tanuki Ramen, 423 5th Ave. They have a waiting list on weekends FYI.", timestamp: "8:27 AM" },
      { id: "gen56", author: "Eve", text: "Random question: does anyone have a good standing desk mat recommendation?", timestamp: "8:30 AM" },
      { id: "gen57", author: "Frank", text: "Yes! The Topo by Ergodriven is great. Got mine on Amazon.", timestamp: "8:31 AM" },
      { id: "gen58", author: "Eve", text: "Thank you!! Ordering now.", timestamp: "8:32 AM" },
      { id: "gen59", author: "Bob", text: "Another Monday survived 🙌", timestamp: "8:45 AM" },
      { id: "gen60", author: "Carol", text: "It's barely 9am Bob 😂", timestamp: "8:46 AM" },
    ],
    threadBrief: {
      main_question: "N/A — general channel",
      current_confusion: "No actionable items.",
      prior_decision: "N/A",
      open_question: "N/A",
    },
  },

  // DM — Alice
  {
    id: "dm-alice",
    channel: "Alice",
    threadTitle: "Alice",
    mentionedBy: "Alice",
    mentionSnippet: "Hey, can we sync on the eval-infra decision?",
    relativeTime: "5m ago",
    isUnread: true,
    isActive: true,
    messages: [
      { id: "da1", author: "Alice", text: "Hey Fanmin, quick sync — are you free to confirm the May 12 decision for the team?", timestamp: "9:01 AM" },
      { id: "da2", author: "Fanmin", text: "Yeah, backend merge is fine, default rollout waits for dashboard parity.", timestamp: "9:03 AM" },
      { id: "da3", author: "Alice", text: "Perfect. And who owns the dashboard parity validation? Nobody claimed it in the thread.", timestamp: "9:04 AM" },
      { id: "da4", author: "Fanmin", text: "Good question — I'll find out and follow up.", timestamp: "9:05 AM" },
      { id: "da5", author: "Alice", text: "Thanks. Also the team is a bit confused about whether Bob's merge blocks the rollout.", timestamp: "9:06 AM" },
    ],
    threadBrief: {
      main_question: "Who owns dashboard parity validation?",
      current_confusion: "Team unclear on whether backend merge blocks rollout.",
      prior_decision: "Backend merge is allowed, default rollout waits for parity.",
      open_question: "Dashboard validation owner still unassigned.",
    },
  },

  // DM — Bob
  {
    id: "dm-bob",
    channel: "Bob",
    threadTitle: "Bob",
    mentionedBy: "Bob",
    mentionSnippet: "The migration PR is up, can you review when you get a chance?",
    relativeTime: "25m ago",
    isUnread: true,
    isActive: true,
    messages: [
      { id: "db1", author: "Bob", text: "Hey, I pushed the API gateway migration PR. Eve flagged the rate limiting threshold — she thinks 100 req/min is too low.", timestamp: "8:40 AM" },
      { id: "db2", author: "Fanmin", text: "What's the current prod throughput?", timestamp: "8:43 AM" },
      { id: "db3", author: "Bob", text: "Peak is around 80 req/min, so 100 gives us some headroom but not much.", timestamp: "8:45 AM" },
      { id: "db4", author: "Bob", text: "The migration PR is up, can you review when you get a chance?", timestamp: "8:52 AM" },
    ],
    threadBrief: {
      main_question: "Is the API gateway migration PR ready to merge?",
      current_confusion: "Rate limiting threshold debate — Eve says 100 req/min is too conservative.",
      prior_decision: "Migration approved in last sprint planning.",
      open_question: "Is 100 req/min threshold acceptable for initial rollout?",
    },
  },

  // DM — Carol
  {
    id: "dm-carol",
    channel: "Carol",
    threadTitle: "Carol",
    mentionedBy: "Carol",
    mentionSnippet: "Reminder: Q3 roadmap items due Thursday",
    relativeTime: "3d ago",
    isUnread: false,
    isActive: false,
    messages: [
      { id: "dc1", author: "Carol", text: "Hi Fanmin, just a reminder that Q3 roadmap items are due Thursday EOD.", timestamp: "May 28" },
      { id: "dc2", author: "Carol", text: "Most TLs have submitted. Just waiting on eval-infra.", timestamp: "May 29" },
      { id: "dc3", author: "Fanmin", text: "On my list, will get it done by Thursday.", timestamp: "May 29" },
      { id: "dc4", author: "Carol", text: "Great, thanks! Doc is at go/q3-roadmap if you need the template.", timestamp: "May 29" },
    ],
    threadBrief: {
      main_question: "Has eval-infra submitted Q3 roadmap items?",
      current_confusion: "Fanmin acknowledged but items not yet added.",
      prior_decision: "Thursday EOD deadline for all TLs.",
      open_question: "Items still outstanding.",
    },
  },

  // DM — Dan
  {
    id: "dm-dan",
    channel: "Dan",
    threadTitle: "Dan",
    mentionedBy: "Dan",
    mentionSnippet: "DB spike is resolved, no action needed from you",
    relativeTime: "1d ago",
    isUnread: false,
    isActive: false,
    messages: [
      { id: "dd1", author: "Dan", text: "Hey, just FYI — the DB connection pool spike last night was a runaway metrics export query. Killed it, pool recovered.", timestamp: "Yesterday 8:00 AM" },
      { id: "dd2", author: "Fanmin", text: "Good catch. Any risk of recurrence?", timestamp: "Yesterday 9:15 AM" },
      { id: "dd3", author: "Dan", text: "Potentially. I'd suggest adding a query timeout for the export job. Can file a ticket if you want.", timestamp: "Yesterday 9:20 AM" },
      { id: "dd4", author: "Fanmin", text: "Yes please, let's track it.", timestamp: "Yesterday 9:22 AM" },
      { id: "dd5", author: "Dan", text: "Done — ticket is EI-2847. Low priority, no rush.", timestamp: "Yesterday 9:25 AM" },
    ],
    threadBrief: {
      main_question: "Is the DB connection pool issue fully resolved?",
      current_confusion: "Resolved but recurrence risk not mitigated.",
      prior_decision: "Runaway export query killed, pool recovered.",
      open_question: "Query timeout ticket filed as EI-2847.",
    },
  },
];

export const FALLBACK_COMPILATION: CompilationResult = {
  intent_parsed: {
    summary: "Clarify that backend merge can proceed, but default rollout should wait for dashboard parity based on the prior decision.",
    bullets: [
      "Backend merge can proceed",
      "Default rollout should wait",
      "Dashboard parity is the blocker",
      "This is based on a previous decision",
    ],
  },
  retrieved_context: [
    {
      type: "past_thread",
      title: "Launch Readiness",
      date: "May 12",
      summary: "Backend merge is allowed, but default rollout is blocked until dashboard parity is validated.",
      reason_relevant: "This directly answers whether unified eval can become the default.",
      score: 0.91,
    },
    {
      type: "doc",
      title: "Release Validation Checklist",
      date: null,
      summary: "Default rollout requires dashboard parity, release reporting validation, and metrics export verification.",
      reason_relevant: "This doc defines the release criteria for default rollout.",
      score: 0.83,
    },
  ],
  draft_reply:
    "We discussed this in the May 12 launch readiness thread. The decision was that backend merge is okay, but making unified eval the default should wait until dashboard parity is validated.",
  verification: {
    grounded_in_context: true,
    clarity: "good",
    misinterpretation_risk: "low",
    grammar: "clean",
    missing_detail: "Owner for dashboard validation is not specified.",
    suggested_follow_up: "Who owns dashboard validation?",
  },
  misinterpretation_detection: {
    detected: true,
    explanation:
      "Bob is answering whether backend code is merged, while Alice is asking whether default rollout is ready. These are related but not the same.",
  },
  final_reply:
    "We discussed this in the May 12 launch readiness thread. The decision was that backend merge is okay, but making unified eval the default should wait until dashboard parity is validated. So we can proceed with the backend merge, but default rollout should stay blocked until dashboard validation is complete. Who owns dashboard validation?",
};

export const FALLBACK_DRAFT_SAFETY: DraftSafety = {
  sources: [
    { title: "Launch Readiness · May 12", type: "thread", visible: true },
    { title: "Release Validation Checklist", type: "doc", visible: true },
    { title: "#eval-infra-private", type: "thread", visible: false },
  ],
  hasRestrictedSource: true,
  confidence: "high",
  staleness: "1 source may be stale",
};

export const FALLBACK_ASK_MEMORY: AskMemoryResult = {
  answer: "Dashboard parity blocks default rollout, but does not block backend merge.",
  sources: [
    {
      type: "past_thread",
      title: "Launch Readiness",
      date: "May 12",
      summary: "Backend merge is allowed, but default rollout is blocked until dashboard parity is validated.",
      score: 0.91,
    },
    {
      type: "doc",
      title: "Release Validation Checklist",
      date: null,
      summary: "Default rollout requires dashboard parity, release reporting validation, and metrics export verification.",
      score: 0.83,
    },
  ],
};

export const focusItems: FocusItem[] = [
  // URGENT
  {
    id: "f5",
    type: "needs_reply",
    state: "needs_response",
    channel: "oncall-p0",
    isDM: false,
    person: "Bob",
    summary: "Production API is at 40% error rate and Bob needs your call on whether to rollback v2.4.1.",
    whyShown: [
      "Bob directly mentioned you.",
      "The message contains urgent blocking language.",
      "You are listed as the on-call TL for this service.",
      "Error rate has been elevated for 8 minutes with no resolution.",
    ],
    suggestedAction: "Draft reply",
    sourceTimestamp: "8m ago",
    confidence: "high",
  },
  {
    id: "f8",
    type: "needs_decision",
    state: "needs_response",
    channel: "product",
    isDM: false,
    person: "Sarah",
    summary: "Sarah needs a go/no-go decision from you by 3pm or the Q3 launch window closes.",
    whyShown: [
      "Sarah directly mentioned you.",
      "The message contains a hard deadline: 3pm.",
      "You are the final approver for this launch.",
      "The launch window is time-sensitive.",
    ],
    suggestedAction: "Draft reply",
    sourceTimestamp: "1h ago",
    confidence: "high",
  },
  {
    id: "f7",
    type: "blocked_on_you",
    state: "needs_response",
    channel: "ml-pipeline",
    isDM: false,
    person: "Alice",
    summary: "The new eval model checkpoint deployment is blocked waiting for your approval.",
    whyShown: [
      "Alice directly mentioned you.",
      "The thread contains blocking language: 'blocked on your approval'.",
      "You own model deployment approvals.",
      "The training run completed 2 hours ago.",
    ],
    suggestedAction: "Open thread",
    sourceTimestamp: "15m ago",
    confidence: "high",
  },
  {
    id: "f9",
    type: "risk_detected",
    state: "needs_response",
    channel: "security",
    isDM: false,
    person: "Eve",
    summary: "CVE-2025-4821 affects the auth library. Eve needs your sign-off on the patch plan before the 24-hour SLA expires.",
    whyShown: [
      "Eve directly mentioned you.",
      "The thread involves a critical CVE with a 24-hour remediation SLA.",
      "You are the security sign-off approver.",
      "Time is running out on the SLA.",
    ],
    suggestedAction: "Draft reply",
    sourceTimestamp: "32m ago",
    confidence: "high",
  },
  {
    id: "f10",
    type: "risk_detected",
    state: "needs_response",
    channel: "design-review",
    isDM: false,
    person: "Jenny",
    summary: "Checkout redesign ships tomorrow at 9am but you haven't approved the final mockups.",
    whyShown: [
      "Jenny directly mentioned you.",
      "Designs launch tomorrow — approval is overdue.",
      "You are the required TL approver.",
      "Eng is blocked from starting implementation.",
    ],
    suggestedAction: "Draft reply",
    sourceTimestamp: "2h ago",
    confidence: "high",
  },
  // Original 4
  {
    id: "f1",
    type: "needs_reply",
    state: "needs_response",
    channel: "eval-infra",
    isDM: false,
    person: "Alice",
    summary: "Alice is asking whether the unified eval rollout is blocked on dashboard parity.",
    whyShown: [
      "Alice directly mentioned you.",
      "The message contains a direct question.",
      "The thread appears blocked until you clarify.",
      "You participated in the May 12 decision thread.",
    ],
    suggestedAction: "Draft reply",
    sourceTimestamp: "Today 9:08 AM",
    confidence: "high",
  },
  {
    id: "f2",
    type: "needs_decision",
    state: "needs_response",
    channel: "platform",
    isDM: false,
    person: "Bob",
    summary: "Bob is requesting your review of the API gateway migration PR before standup.",
    whyShown: [
      "Bob directly mentioned you.",
      "The message contains approval language.",
      "The PR appears to be waiting on your sign-off.",
    ],
    suggestedAction: "Open thread",
    sourceTimestamp: "Today 8:52 AM",
    confidence: "high",
  },
  {
    id: "f3",
    type: "follow_up_due",
    state: "needs_response",
    channel: "planning",
    isDM: false,
    person: "Carol",
    summary: "Carol asked you to add eval-infra Q3 roadmap items by Thursday.",
    whyShown: [
      "Carol directly mentioned you.",
      "The message contains a deadline: Thursday.",
      "No response has been sent from you in this thread.",
    ],
    suggestedAction: "Draft reply",
    sourceTimestamp: "3 days ago",
    confidence: "medium",
  },
  {
    id: "f4",
    type: "fyi",
    state: "needs_response",
    channel: "infra",
    isDM: false,
    person: "Dan",
    summary: "Dan resolved the DB connection pool spike and mentioned you as an FYI.",
    whyShown: [
      "Dan mentioned you.",
      "The message is informational — no action required.",
      "The thread is marked as resolved.",
    ],
    suggestedAction: "Dismiss",
    sourceTimestamp: "Yesterday 8:00 AM",
    confidence: "high",
  },
  {
    id: "f6",
    type: "follow_up_due",
    state: "needs_response",
    channel: "design-review",
    isDM: false,
    person: "Jenny",
    summary: "You were asked to review the checkout flow designs 2 days ago. Launch is tomorrow.",
    whyShown: [
      "You were tagged as a required reviewer.",
      "Deadline is approaching — designs ship tomorrow.",
      "No review submitted yet.",
    ],
    suggestedAction: "Open thread",
    sourceTimestamp: "2 days ago",
    confidence: "medium",
  },
];

export const waitingItems: WaitingItem[] = [
  {
    id: "w1",
    person: "Carol",
    question: "Who is responsible for owning the dashboard parity validation?",
    originalReason: "Alice asked in #eval-infra and no owner was identified in the thread or prior decisions.",
    status: "waiting",
    sentAt: "1h ago",
  },
  {
    id: "w2",
    person: "Eve",
    question: "Is the rate limiting threshold in the API gateway migration PR correct?",
    originalReason: "Eve raised a concern in #platform and I couldn't find a definitive answer in the docs.",
    status: "answered",
    sentAt: "2h ago",
    answer: "Eve confirmed the threshold is intentionally conservative at 100 req/min and will be raised after monitoring the initial rollout.",
  },
];

export const archiveItems: ArchiveItem[] = [
  {
    id: "a1",
    originalType: "needs_decision",
    summary: "Approved backend merge to proceed without waiting for dashboard parity.",
    resolvedAt: "May 12",
    channel: "eval-infra",
    person: "Alice",
  },
  {
    id: "a2",
    originalType: "fyi",
    summary: "Metrics export is working correctly. Release reporting still needs validation.",
    resolvedAt: "May 15",
    channel: "metrics-dashboard",
    person: "Carol",
  },
  {
    id: "a3",
    originalType: "risk_detected",
    summary: "Release reporting does not match legacy dashboard — flagged as launch blocker.",
    resolvedAt: "May 15",
    channel: "metrics-dashboard",
    person: "Dan",
  },
];
